version: '3.4'

services:
  backendapi:
    networks:
      - default
    build:
      context: ./src
      dockerfile: BackendApi/Dockerfile
    ports:
      - "5002:8080"
      - "5003:8081"
    environment:
      - InfluxDB__Host=${INFLUXDB_HOST}
      - InfluxDB__AdminToken=${INFLUXDB_ADMIN_TOKEN}
      - InfluxDB__Bucket=${INFLUXDB_BUCKET}
      - InfluxDB__Organization=${INFLUXDB_ORG}
  thingsapi:
    networks:
      - default
    build:
      context: ./src
      dockerfile: ThingsApi/Dockerfile
    ports:
      - "5004:8080"
      - "5005:8081"
    environment:
      - InfluxDB__Host=${INFLUXDB_HOST}
      - InfluxDB__AdminToken=${INFLUXDB_ADMIN_TOKEN}
      - InfluxDB__Bucket=${INFLUXDB_BUCKET}
      - InfluxDB__Organization=${INFLUXDB_ORG}
  frontend:
    networks:
      - default
    build:
      context: ./src
      dockerfile: Frontend/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - BackendApi__Url=http://backendapi:8080
      - InfluxDB__AdminToken=${INFLUXDB_ADMIN_TOKEN}
      - InfluxDB__Bucket=${INFLUXDB_BUCKET}
      - InfluxDB__Organization=${INFLUXDB_ORG}
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - c:/temp/docker/influxdb2:/etc/influxdb2
      - c:/temp/docker/influxdb2/db:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default