apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: weather-dr
  namespace: {{ .Values.namespace.name }}
spec:
  host: weather
  subsets:
  - name: {{ .Values.weather.version | default "v1" }}
    labels:
      version: {{ .Values.weather.version | default "v1" }}