apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weatherstation.fullname" . }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "weatherstation.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "weatherstation.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
      version: v1
  template:
    metadata:
      labels:
        {{- include "weatherstation.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
        version: v1
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: {{ .Values.postgres.port }}
          name: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "weatherstation.fullname" . }}-postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "weatherstation.fullname" . }}-postgres-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "weatherstation.fullname" . }}-postgres-pvc