apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weatherstation.fullname" . }}-postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "weatherstation.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}