apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: things
  namespace: {{ .Values.namespace.name }}
spec:
  host: things
  subsets:
  - name: {{ .Values.things.version | default "v1" }}
    labels:
      version: {{ .Values.things.version | default "v1" }}
  trafficPolicy:
    tls:
      mode: DISABLE