namespace:
  name: weatherstation

frontend:
  image: sebastart/weatherstation:latest
  host: weatherstation.wondering-developer.de
  replicas: 1
  port: 80
  version: "v1"
  
influxdb:
  version: "v1"
  image: influxdb:2.7.1
  port: 8086
  pvc:
    size: 10Gi
  secrets:
    DOCKER_INFLUXDB_INIT_MODE: setup
    DOCKER_INFLUXDB_INIT_USERNAME: admin
    DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
    DOCKER_INFLUXDB_INIT_ORG: organization
    DOCKER_INFLUXDB_INIT_BUCKET: bucket
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-secret-dev-token