namespace:
  name: weatherstation
istio:
  revision: default

frontend:
  image: sebastart/frontend
  imageVersion: "latest"
  host: weatherstation.wondering-developer.de
  replicas: 1
  port: 80
  targetPort: 8080
  version: "v1"

weather:
  image: sebastart/temperature-dashboard
  imageVersion: "latest"
  host: weather.wondering-developer.de
  replicas: 1
  port: 80
  targetPort: 3000
  version: "v1"

things:
  image: sebastart/thingsapi
  imageVersion: "latest"
  host: things.wondering-developer.de
  replicas: 1
  port: 80
  targetPort: 8080
  version: "v1"

backend:
  image: sebastart/backendapi
  imageVersion: "latest"
  host: weatherstation.wondering-developer.de
  replicas: 1
  port: 80
  targetPort: 8080
  version: "v1"
  secrets:
    OPEN_WEATHER_MAP_API_KEY: ""
  weatherCache:
    refreshIntervalMinutes: 60

postgres:
  database: weatherstation
  username: weatherstation
  password: ""
  port: 5432
  storage: 1Gi

influxdb:
  host: http://influxdb
  version: "v1"
  image: influxdb:2.7.1
  port: 8086
  pvc:
    size: 5Gi
  secrets:
    INFLUXDB_INIT_MODE: setup
    INFLUXDB_INIT_USERNAME: admin
    INFLUXDB_INIT_PASSWORD: adminadmin
    INFLUXDB_INIT_ORG: organization
    INFLUXDB_INIT_BUCKET: bucket
    INFLUXDB_INIT_ADMIN_TOKEN: my-secret-dev-token