apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: weatherstation
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto
  labels:
    istio-injection: enabled