apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  namespace: weatherstation
  labels:
    app: influxdb
    version: v1
spec:
  selector:
    matchLabels:
      app: influxdb
      version: v1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb
        version: v1
    spec:
      containers:
      - image: influxdb:2.7.1
        name: influxdb
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /etc/influxdb2
          name: influxdb-storage
        - mountPath: /var/lib/influxdb2
          name: influxdb-storage
        envFrom:
        - secretRef:
            name: influxdb-secrets
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc