apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: weatherstation
  labels:
    app: influxdb
    service: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    protocol: TCP
    port: 8086
    targetPort: 8086