apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  InfluxDB__Host: {{ .Values.influxdb.host }}
  InfluxDB__Organization: {{ .Values.influxdb.secrets.INFLUXDB_INIT_ORG | b64enc }}
  InfluxDB__Bucket: {{ .Values.influxdb.secrets.INFLUXDB_INIT_BUCKET | b64enc }}
  InfluxDB__AdminToken: {{ .Values.influxdb.secrets.INFLUXDB_INIT_ADMIN_TOKEN | b64enc }}
