apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  InfluxDB__Host: {{ printf "%s:%d" .Values.influxdb.host (int .Values.influxdb.port) | b64enc }}
  InfluxDB__Organization: {{ .Values.influxdb.secrets.INFLUXDB_INIT_ORG | b64enc }}
  InfluxDB__Bucket: {{ .Values.influxdb.secrets.INFLUXDB_INIT_BUCKET | b64enc }}
  InfluxDB__AdminToken: {{ .Values.influxdb.secrets.INFLUXDB_INIT_ADMIN_TOKEN | b64enc }}
  OpenWeatherMap__ApiKey: {{ .Values.backend.secrets.OPEN_WEATHER_MAP_API_KEY | b64enc }}
  ConnectionStrings__DefaultConnection: {{ printf "Host=%s-postgres-service;Database=%s;Username=%s;Password=%s" (include "weatherstation.fullname" .) .Values.postgres.database .Values.postgres.username .Values.postgres.password | b64enc }}
  WeatherCache__RefreshIntervalMinutes: {{ .Values.backend.weatherCache.refreshIntervalMinutes | toString | b64enc }}
