apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.targetPort }}