apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-vs
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
  - {{ .Values.backend.host }}
  gateways:
  - default/ingress-gateway
  http:
  - route:
    - destination:
        host: backend
        subset: {{ .Values.influxdb.version | default "v1" }}
        port:
          number: {{ .Values.backend.port }}