apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Values.frontend.version | default "v1" }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
          - containerPort: {{ .Values.frontend.port }}
          envFrom:
          - secretRef:
              name: influxdb-secrets
      imagePullSecrets:
        - name: docker-container-registry