apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  INFLUXDB_INIT_MODE: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_MODE }}
  INFLUXDB_INIT_USERNAME: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_USERNAME }}
  INFLUXDB_INIT_PASSWORD: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_PASSWORD }}
  INFLUXDB_INIT_ORG: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_ORG }}
  INFLUXDB_INIT_BUCKET: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_BUCKET }}
  INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.influxdb.secrets.DOCKER_INFLUXDB_INIT_ADMIN_TOKEN }}
