apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}