apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: {{ .Values.namespace.name }}
  labels:
    app: influxdb
    service: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.influxdb.port }}
    targetPort: {{ .Values.influxdb.port }}