apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weatherstation-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.frontend.host }}
  gateways:
  - default/ingress-gateway
  http:
  - route:
    - destination:
        host: frontend
        subset: {{ .Values.influxdb.version | default "v1" }}
        port:
          number: {{ .Values.frontend.port }}