apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: weatherstation
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: weatherstation-gateway
  namespace: weatherstation
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-weatherstation
      protocol: HTTP
    hosts:
    - "130.61.108.242.nip.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weatherstation-vs
  namespace: weatherstation
spec:
  hosts:
  - "130.61.108.242.nip.io"
  gateways:
  - weatherstation-gateway
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: weatherstation
  namespace: weatherstation
spec:
  host: frontend
  subsets:
  - name: v1
    labels:
      version: v1
  trafficPolicy:
    tls:
      mode: DISABLE