version: '3.4'

services:
  thingsApi:
    build:
      context: ../
      dockerfile: ThingsApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - InfluxDB__Host=${INFLUXDB_HOST}
      - InfluxDB__AdminToken=${INFLUXDB_ADMIN_TOKEN}
      - InfluxDB__Bucket=${INFLUXDB_BUCKET}
      - InfluxDB__Organization=${INFLUXDB_ORG}
    networks:
      - default

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - c:/temp/docker/influxdb2:/etc/influxdb2
      - c:/temp/docker/influxdb2/db:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default