apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Values.frontend.version | default "v1" }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}:{{ .Values.backend.imageVersion }}
          ports:
          - containerPort: {{ .Values.frontend.port }}
          env:
            - name: BackendApi__Url
              value: "http://backend/"
      imagePullSecrets:
        - name: docker-container-registry