apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: weatherstation
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: sebastart/weatherstation:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-container-registry