apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: tcp-mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
      appProtocol: tcp