apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: openid
    openid:
      client_id: "kiali"
      username_claim: "email"
      disable_rbac: true
      issuer_uri: "https://keycloak.wondering-developer.de/realms/telemetry"
  deployment:
    view_only_mode: false