apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    app: influxdb
    version: {{ .Values.influxdb.version | default "v1" }}
spec:
  selector:
    matchLabels:
      app: influxdb
      version: {{ .Values.influxdb.version | default "v1" }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb
        version: {{ .Values.influxdb.version | default "v1" }}
    spec:
      containers:
      - image: {{ .Values.influxdb.image }}
        name: influxdb
        ports:
        - containerPort: {{ .Values.influxdb.port }}
        volumeMounts:
        - mountPath: /etc/influxdb2
          name: influxdb-storage
        - mountPath: /var/lib/influxdb2
          name: influxdb-storage
        envFrom:
        - secretRef:
            name: influxdb-secrets
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc