version: '3.4'

services:
  backendapi:
    build:
      context: ../
      dockerfile: BackendApi/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - InfluxDB__Host=${INFLUXDB_HOST}
      - InfluxDB__AdminToken=${INFLUXDB_ADMIN_TOKEN}
      - InfluxDB__Bucket=${INFLUXDB_BUCKET}
      - InfluxDB__Organization=${INFLUXDB_ORG}
      - OpenWeatherMap__ApiKey=${OPEN_WEATHER_MAP_API_KEY}
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - WeatherCache__RefreshIntervalMinutes=${WEATHER_CACHE_INTERVAL_MINUTES}
    depends_on:
      - postgres
      - influxdb
    networks:
      - default

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - c:/temp/docker/influxdb2:/etc/influxdb2
      - c:/temp/docker/influxdb2/db:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - default

  seed-influxdb:
    image: alpine:latest
    depends_on:
      - influxdb
    volumes:
      - ./seed-influxdb.sh:/seed-influxdb.sh:ro
    environment:
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    entrypoint: ["/bin/sh", "/seed-influxdb.sh"]
    networks:
      - default

  postgres:
    image: postgres:15-alpine
    container_name: postgres-backendapi
    ports:
      - "5432:5432"
    volumes:
      - c:/temp/docker/postgres-backendapi:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - default
