FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR src
COPY ["BackendApi/BackendApi.csproj", "BackendApi/"]
COPY ["Application/Application.csproj", "Application/"]
RUN dotnet restore "BackendApi/BackendApi.csproj"

COPY ["src/BackendApi", "BackendApi/"]
COPY ["src/Application", "Application/"]
RUN dotnet build "BackendApi/BackendApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BackendApi/BackendApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InputApi.dll"]