FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/OldThingsApi
RUN dotnet restore "OldThingsApi.csproj"
RUN dotnet build "OldThingsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OldThingsApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "OldThingsApi.dll"]