FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR src
COPY ["Weatherstation/Weatherstation.csproj", "Weatherstation/"]
RUN dotnet restore "Weatherstation/Weatherstation.csproj" --verbosity detailed

COPY ["Weatherstation", "Weatherstation/"]
RUN dotnet build "Weatherstation/Weatherstation.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Weatherstation/Weatherstation.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Weatherstation.dll"]
