FROM mcr.microsoft.com/dotnet/runtime-deps:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
ARG BUILDPLATFORM

WORKDIR /src
COPY ["ThingsApi", "src/ThingsApi/"]
COPY ["Application", "src/Application/"]
RUN dotnet restore "src/ThingsApi/ThingsApi.csproj"

RUN dotnet build "src/ThingsApi/ThingsApi.csproj" -c Release -o /app/build -a $TARGETARCH

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "ThingsApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ThingsApi.dll"]
