FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ThingsApi/ThingsApi.csproj", "ThingsApi/"]
COPY ["Application/Application.csproj", "Application/"]
RUN dotnet restore "ThingsApi/ThingsApi.csproj"

COPY ["ThingsApi", "ThingsApi/"]
COPY ["Application", "Application/"]
RUN dotnet build "ThingsApi/ThingsApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ThingsApi/ThingsApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InputApi.dll"]