apiVersion: v1

kind: Secret
metadata:
  name: influxdb-secrets
  namespace: weatherstation
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  DOCKER_INFLUXDB_INIT_PASSWORD: adminadmin
  DOCKER_INFLUXDB_INIT_ORG: organization
  DOCKER_INFLUXDB_INIT_BUCKET: bucket
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-secret-dev-token