name: InputApi-Deployment

on:
  workflow_dispatch:
    inputs:
      baseversion:
        description: 'Image base version'
        required: true
        default: '0.5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: sebastart/weatherstation
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare
        id: prepare
        run: |
          echo "DOCKER_PLATFORM=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
          VERSION="${{ github.event.inputs.baseversion }}.$GITHUB_RUN_NUMBER"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo ::set-output name=version::$VERSION

      - name: Log into registry docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        working-directory: src
        run: |
          docker buildx build . \
            --platform $DOCKER_TARGET_PLATFORM \
            --file ./InputApi/Dockerfile \
            --tag $DOCKER_IMAGE:${{ steps.prepare.outputs.version }} \
            --tag $DOCKER_IMAGE:latest \
            --output type=image,push=true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.20.0'

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          
      - name: Deploy with Helm
        run: |
          chmod 600 /home/runner/.kube/config
          helm upgrade --install weatherstation ./helm/weatherstation --namespace weatherstation --create-namespace --set influxdb.secrets.INFLUXDB_INIT_USERNAME=${{ secrets.INFLUXDB_USERNAME }}, influxdb.secrets.INFLUXDB_INIT_PASSWORD=${{ secrets.INFLUXDB_INIT_PASSWORD }}, influxdb.secrets.INFLUXDB_INIT_ADMIN_TOKEN=${{ secrets.INFLUXDB_INIT_ADMIN_TOKEN }}
    
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/frontend -n weatherstation
